services:
    streamflow-db:
        platform: linux/amd64
        container_name: streamflow-db
        restart: always
        healthcheck: 
            interval: 10s
            retries: 10
            test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
            timeout: 2s
        image: timescale/timescaledb-ha:pg16
        ports: 
            - "5434:5432"
        volumes:
            - streamflow-data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - .env
    streamflow-api:
        container_name: streamflow-api
        restart: always
        build: .
        env_file:
            - .env
        ports:
            - "8000:80"
        networks:
            - streamflow-net

volumes:
    streamflow-data: {}

networks:
    streamflow-net:
        external: true